In [14]:
import polars as pl

recipes = pl.read_parquet("recipes.parquet")
reviews = pl.read_parquet("reviews.parquet")

print("=== recipes.parquet ===")
print(f"Shape: {recipes.shape}")
print(recipes.dtypes)
print(recipes.head())

print("\n=== reviews.parquet ===")
print(f"Shape: {reviews.shape}")
print(reviews.dtypes)
print(reviews.head())

=== recipes.parquet ===
Shape: (522517, 28)
[Float64, String, Int32, String, String, String, String, Datetime(time_unit='us', time_zone='UTC'), String, List(String), String, List(String), List(String), List(String), Float64, Int32, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Float64, Int32, String, List(String)]
shape: (5, 28)
┌──────────┬────────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ RecipeId ┆ Name       ┆ AuthorId ┆ AuthorNam ┆ … ┆ ProteinCo ┆ RecipeSer ┆ RecipeYie ┆ RecipeIns │
│ ---      ┆ ---        ┆ ---      ┆ e         ┆   ┆ ntent     ┆ vings     ┆ ld        ┆ tructions │
│ f64      ┆ str        ┆ i32      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│          ┆            ┆          ┆ str       ┆   ┆ f64       ┆ i32       ┆ str       ┆ list[str] │
╞══════════╪════════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 38.0     ┆ Low-Fat    ┆ 1533     ┆ Dancer    ┆ … ┆ 3.2       ┆ 4         ┆ null      ┆ ["Toss 2  │
│          ┆ Berry Blue ┆          ┆           ┆   ┆           ┆           ┆           ┆ cups      │
│          ┆ Frozen     ┆          ┆           ┆   ┆           ┆           ┆           ┆ berries   │
│          ┆ Dess…      ┆          ┆           ┆   ┆           ┆           ┆           ┆ with sug… │
│ 39.0     ┆ Biryani    ┆ 1567     ┆ elly9812  ┆ … ┆ 63.4      ┆ 6         ┆ null      ┆ ["Soak    │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ saffron   │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ in warm   │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ milk fo…  │
│ 40.0     ┆ Best       ┆ 1566     ┆ Stephen   ┆ … ┆ 0.3       ┆ 4         ┆ null      ┆ ["Into a  │
│          ┆ Lemonade   ┆          ┆ Little    ┆   ┆           ┆           ┆           ┆ 1 quart   │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ Jar with  │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ tigh…     │
│ 41.0     ┆ Carina's   ┆ 1586     ┆ Cyclopz   ┆ … ┆ 29.3      ┆ 2         ┆ 4 kebabs  ┆ ["Drain   │
│          ┆ Tofu-Veget ┆          ┆           ┆   ┆           ┆           ┆           ┆ the tofu, │
│          ┆ able       ┆          ┆           ┆   ┆           ┆           ┆           ┆ carefully │
│          ┆ Kebabs     ┆          ┆           ┆   ┆           ┆           ┆           ┆ sq…       │
│ 42.0     ┆ Cabbage    ┆ 1538     ┆ Duckie067 ┆ … ┆ 4.3       ┆ 4         ┆ null      ┆ ["Mix eve │
│          ┆ Soup       ┆          ┆           ┆   ┆           ┆           ┆           ┆ rything   │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ together  │
│          ┆            ┆          ┆           ┆   ┆           ┆           ┆           ┆ and …     │
└──────────┴────────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

=== reviews.parquet ===
Shape: (1401982, 8)
[Int32, Int32, Int32, String, Int32, String, Datetime(time_unit='us', time_zone='UTC'), Datetime(time_unit='us', time_zone='UTC')]
shape: (5, 8)
┌──────────┬──────────┬──────────┬──────────────┬────────┬─────────────┬─────────────┬─────────────┐
│ ReviewId ┆ RecipeId ┆ AuthorId ┆ AuthorName   ┆ Rating ┆ Review      ┆ DateSubmitt ┆ DateModifie │
│ ---      ┆ ---      ┆ ---      ┆ ---          ┆ ---    ┆ ---         ┆ ed          ┆ d           │
│ i32      ┆ i32      ┆ i32      ┆ str          ┆ i32    ┆ str         ┆ ---         ┆ ---         │
│          ┆          ┆          ┆              ┆        ┆             ┆ datetime[μs ┆ datetime[μs │
│          ┆          ┆          ┆              ┆        ┆             ┆ , UTC]      ┆ , UTC]      │
╞══════════╪══════════╪══════════╪══════════════╪════════╪═════════════╪═════════════╪═════════════╡
│ 2        ┆ 992      ┆ 2008     ┆ gayg msft    ┆ 5      ┆ better than ┆ 2000-01-25  ┆ 2000-01-25  │
│          ┆          ┆          ┆              ┆        ┆ any you can ┆ 21:44:00    ┆ 21:44:00    │
│          ┆          ┆          ┆              ┆        ┆ get at…     ┆ UTC         ┆ UTC         │
│ 7        ┆ 4384     ┆ 1634     ┆ Bill         ┆ 4      ┆ I cut back  ┆ 2001-10-17  ┆ 2001-10-17  │
│          ┆          ┆          ┆ Hilbrich     ┆        ┆ on the      ┆ 16:49:59    ┆ 16:49:59    │
│          ┆          ┆          ┆              ┆        ┆ mayo, and   ┆ UTC         ┆ UTC         │
│          ┆          ┆          ┆              ┆        ┆ ma…         ┆             ┆             │
│ 9        ┆ 4523     ┆ 2046     ┆ Gay Gilmore  ┆ 2      ┆ i think i   ┆ 2000-02-25  ┆ 2000-02-25  │
│          ┆          ┆          ┆ ckpt         ┆        ┆ did         ┆ 09:00:00    ┆ 09:00:00    │
│          ┆          ┆          ┆              ┆        ┆ something   ┆ UTC         ┆ UTC         │
│          ┆          ┆          ┆              ┆        ┆ wrong …     ┆             ┆             │
│ 13       ┆ 7435     ┆ 1773     ┆ Malarkey     ┆ 5      ┆ easily the  ┆ 2000-03-13  ┆ 2000-03-13  │
│          ┆          ┆          ┆ Test         ┆        ┆ best i have ┆ 21:15:00    ┆ 21:15:00    │
│          ┆          ┆          ┆              ┆        ┆ ever ha…    ┆ UTC         ┆ UTC         │
│ 14       ┆ 44       ┆ 2085     ┆ Tony Small   ┆ 5      ┆ An          ┆ 2000-03-28  ┆ 2000-03-28  │
│          ┆          ┆          ┆              ┆        ┆ excellent   ┆ 12:51:00    ┆ 12:51:00    │
│          ┆          ┆          ┆              ┆        ┆ dish.       ┆ UTC         ┆ UTC         │
└──────────┴──────────┴──────────┴──────────────┴────────┴─────────────┴─────────────┴─────────────┘

In [17]:
recipes = recipes.with_columns(pl.col("RecipeId").cast(pl.Int32))

merged = reviews.join(recipes, on="RecipeId", how="inner", suffix="_recipe")

print(f"recipes rows:  {len(recipes):,}")
print(f"reviews rows:  {len(reviews):,}")
print(f"merged rows:   {len(merged):,}")
print(f"merged cols:   {len(merged.columns)}")
print(merged.head())

merged.write_parquet("merged.parquet")
print("\nSaved to merged.parquet")

recipes rows:  522,517
reviews rows:  1,401,982
merged rows:   1,401,963
merged cols:   35
shape: (5, 35)
┌──────────┬──────────┬──────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ ReviewId ┆ RecipeId ┆ AuthorId ┆ AuthorName ┆ … ┆ ProteinCon ┆ RecipeSer ┆ RecipeYie ┆ RecipeIns │
│ ---      ┆ ---      ┆ ---      ┆ ---        ┆   ┆ tent       ┆ vings     ┆ ld        ┆ tructions │
│ i32      ┆ i32      ┆ i32      ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│          ┆          ┆          ┆            ┆   ┆ f64        ┆ i32       ┆ str       ┆ list[str] │
╞══════════╪══════════╪══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2        ┆ 992      ┆ 2008     ┆ gayg msft  ┆ … ┆ 4.3        ┆ 24        ┆ null      ┆ ["In a    │
│          ┆          ┆          ┆            ┆   ┆            ┆           ┆           ┆ mixing    │
│          ┆          ┆          ┆            ┆   ┆            ┆           ┆           ┆ bowl,     │
│          ┆          ┆          ┆            ┆   ┆            ┆           ┆           ┆ combine   │
│          ┆          ┆          ┆            ┆   ┆            ┆           ┆           ┆ ch…       │
│ 7        ┆ 4384     ┆ 1634     ┆ Bill       ┆ … ┆ 0.2        ┆ 4         ┆ null      ┆ ["Combine │
│          ┆          ┆          ┆ Hilbrich   ┆   ┆            ┆           ┆           ┆ all in a  │
│          ┆          ┆          ┆            ┆   ┆            ┆           ┆           ┆ bowl and  │
│          ┆          ┆          ┆            ┆   ┆            ┆           ┆           ┆ mi…       │
│ 9        ┆ 4523     ┆ 2046     ┆ Gay        ┆ … ┆ 43.0       ┆ 8         ┆ null      ┆ ["Combine │
│          ┆          ┆          ┆ Gilmore    ┆   ┆            ┆           ┆           ┆ all ingre │
│          ┆          ┆          ┆ ckpt       ┆   ┆            ┆           ┆           ┆ dients    │
│          ┆          ┆          ┆            ┆   ┆            ┆           ┆           ┆ for …     │
│ 13       ┆ 7435     ┆ 1773     ┆ Malarkey   ┆ … ┆ 47.0       ┆ 12        ┆ null      ┆ ["Use a   │
│          ┆          ┆          ┆ Test       ┆   ┆            ┆           ┆           ┆ 14 to 20  │
│          ┆          ┆          ┆            ┆   ┆            ┆           ┆           ┆ qt.       │
│          ┆          ┆          ┆            ┆   ┆            ┆           ┆           ┆ pan.",    │
│          ┆          ┆          ┆            ┆   ┆            ┆           ┆           ┆ "C…       │
│ 14       ┆ 44       ┆ 2085     ┆ Tony Small ┆ … ┆ 45.3       ┆ 2         ┆ null      ┆ ["Melt 1  │
│          ┆          ┆          ┆            ┆   ┆            ┆           ┆           ┆ 1/2 ozs   │
│          ┆          ┆          ┆            ┆   ┆            ┆           ┆           ┆ butter,   │
│          ┆          ┆          ┆            ┆   ┆            ┆           ┆           ┆ add t…    │
└──────────┴──────────┴──────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

Saved to merged.parquet

In [1]:
import polars as pl

merged = pl.read_parquet("data/merged.parquet")

In [3]:
merged['Review']

shape: (1_401_963,)
Series: 'Review' [str]
[
	"better than any you can get at…
	"I cut back on the mayo, and ma…
	"i think i did something wrong …
	"easily the best i have ever ha…
	"An excellent dish."
	…
	"I was disappointed. I couldn't…
	"Nothing to drain. And I don’t …
	"Good base recipe for someone t…
	"Thank you so much for this ama…
	"I can't say enough about this …
]

In [24]:
merged['RecipeInstructions'].head()

shape: (10,)
Series: 'RecipeInstructions' [list[str]]
[
	["In a mixing bowl, combine cheeses, bacon and seasonings.; mix well.", "Spoon about  2 Tbs. into each pepper half.", … "NOTES : When cutting or seeding hot peppers, use rubber or plastic gloves to  protect your hands. avoid touching your face. I omit the bacon in this recipe."]
	["Combine all in a bowl and mix thoroughly.", "Cover and chill at least 2 hours.", "Use for dip with raw vegetables."]
	["Combine all ingredients for sauce in a quart jar with a lid and shake gently.   Store in refrigerator until ready for use.", "Mix chicken, soy sauce, and pepper.  Stir in egg.  Add cornstarch, and mix until chicken pieces are coated.", … "Serve with fried or steamed rice. Enjoy!"]
	["Use a 14 to 20 qt. pan.", "Coarsely chop enough onions and carrots to make 1 cup each.", … "Serve meat and vegetables with mustards."]
	["Melt 1 1/2 ozs butter, add the flour and cook for 2 to 3 minutes, stirring.", "Gradually add milk and cook, stirring, until thick and smooth.", … "Transfer to a serving dish and sprinkle with chopped parsley."]
	["Put all the salad ingredients above in a large bowl.", "Combine all dressing ingredients in a shaker bottle and shake vigorously.  Pour over above salad.", "Serve immediately."]
	["Measure oatmeal and blend in a blender to a fine powder.", "Cream the butter and both sugars.", … "Bake for 10 minutes at 375° or until golden."]
	["How to assemble: Slice roll horizontally, about 1/2 inch from bottom.", "Pull out  bread from top half, leaving walls about 1/2 inch thick.", … "Attach using mayonnaise."]
	["Preheat oven to 350 degrees Fahrenheit.", "Mix lamb and hamburger together.", … "Bake for 70 to 80 minutes."]
	["Mix honey with chilies, mustard, lime juice, garlic, cumin, allspice, and cilantro.", "Season to taste with salt and pepper.", … "Slice steak against the grain and pour remaining marinade over meat."]
]

In [ ]:
null_counts = merged.null_count()
null_cols = {col: null_counts[col][0] for col in null_counts.columns if null_counts[col][0] > 0}

if not null_cols:
    print("No null values found in merged.parquet")
else:
    print(f"Columns with null values ({len(null_cols)} out of {len(merged.columns)}):\n")
    for col, count in null_cols.items():
        print(f"  {col}: {count:,}")
    total_nulls = sum(null_cols.values())
    total_cells = len(merged) * len(merged.columns)
    print(f"\nTotal null cells: {total_nulls:,} / {total_cells:,} ({total_nulls / total_cells * 100:.2f}%)")

In [ ]:
before = len(merged)
merged = merged.drop_nulls()
after = len(merged)

print(f"Dropped {before - after:,} rows with null values")
print(f"Remaining rows: {after:,}")

merged.write_parquet("merged.parquet")
print("Saved to merged.parquet")

In [25]:
dupe_count = len(merged) - merged.unique(subset=["RecipeId"]).shape[0]
print(f"Duplicate RecipeId rows: {dupe_count:,} (expected — multiple reviews per recipe)")
print(f"Unique RecipeIds in merged: {merged['RecipeId'].n_unique():,}")

drop_cols = ["AuthorId", "AuthorName", "AuthorId_recipe", "AuthorName_recipe", "RecipeIngredientQuantities"]
merged = merged.drop(drop_cols)

print(f"\nDropped columns: {drop_cols}")
print(f"Remaining columns ({len(merged.columns)}): {merged.columns}")

merged.write_parquet("merged.parquet")
print("\nSaved to merged.parquet")

Duplicate RecipeId rows: 1,130,289 (expected — multiple reviews per recipe)
Unique RecipeIds in merged: 271,674

Dropped columns: ['AuthorId', 'AuthorName', 'AuthorId_recipe', 'AuthorName_recipe', 'RecipeIngredientQuantities']
Remaining columns (30): ['ReviewId', 'RecipeId', 'Rating', 'Review', 'DateSubmitted', 'DateModified', 'Name', 'CookTime', 'PrepTime', 'TotalTime', 'DatePublished', 'Description', 'Images', 'RecipeCategory', 'Keywords', 'RecipeIngredientParts', 'AggregatedRating', 'ReviewCount', 'Calories', 'FatContent', 'SaturatedFatContent', 'CholesterolContent', 'SodiumContent', 'CarbohydrateContent', 'FiberContent', 'SugarContent', 'ProteinContent', 'RecipeServings', 'RecipeYield', 'RecipeInstructions']

Saved to merged.parquet

In [39]:
import polars as pl

merged = pl.read_parquet("merged.parquet")
merged.head()

shape: (5, 26)
┌──────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ RecipeId ┆ Rating ┆ Review     ┆ Name       ┆ … ┆ ProteinCon ┆ RecipeSer ┆ RecipeYie ┆ RecipeIns │
│ ---      ┆ ---    ┆ ---        ┆ ---        ┆   ┆ tent       ┆ vings     ┆ ld        ┆ tructions │
│ i32      ┆ i32    ┆ str        ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│          ┆        ┆            ┆            ┆   ┆ f64        ┆ i32       ┆ str       ┆ list[str] │
╞══════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 992      ┆ 5      ┆ better     ┆ Jalapeno   ┆ … ┆ 4.3        ┆ 24        ┆ null      ┆ ["In a    │
│          ┆        ┆ than any   ┆ Pepper     ┆   ┆            ┆           ┆           ┆ mixing    │
│          ┆        ┆ you can    ┆ Poppers    ┆   ┆            ┆           ┆           ┆ bowl,     │
│          ┆        ┆ get at…    ┆            ┆   ┆            ┆           ┆           ┆ combine   │
│          ┆        ┆            ┆            ┆   ┆            ┆           ┆           ┆ ch…       │
│ 4384     ┆ 4      ┆ I cut back ┆ Curry Dip  ┆ … ┆ 0.2        ┆ 4         ┆ null      ┆ ["Combine │
│          ┆        ┆ on the     ┆            ┆   ┆            ┆           ┆           ┆ all in a  │
│          ┆        ┆ mayo, and  ┆            ┆   ┆            ┆           ┆           ┆ bowl and  │
│          ┆        ┆ ma…        ┆            ┆   ┆            ┆           ┆           ┆ mi…       │
│ 4523     ┆ 2      ┆ i think i  ┆ Chinese    ┆ … ┆ 43.0       ┆ 8         ┆ null      ┆ ["Combine │
│          ┆        ┆ did        ┆ Imperial   ┆   ┆            ┆           ┆           ┆ all ingre │
│          ┆        ┆ something  ┆ Palace     ┆   ┆            ┆           ┆           ┆ dients    │
│          ┆        ┆ wrong …    ┆ Genera…    ┆   ┆            ┆           ┆           ┆ for …     │
│ 7435     ┆ 5      ┆ easily the ┆ Kevin's    ┆ … ┆ 47.0       ┆ 12        ┆ null      ┆ ["Use a   │
│          ┆        ┆ best i     ┆ Best       ┆   ┆            ┆           ┆           ┆ 14 to 20  │
│          ┆        ┆ have ever  ┆ Corned     ┆   ┆            ┆           ┆           ┆ qt.       │
│          ┆        ┆ ha…        ┆ Beef       ┆   ┆            ┆           ┆           ┆ pan.",    │
│          ┆        ┆            ┆            ┆   ┆            ┆           ┆           ┆ "C…       │
│ 44       ┆ 5      ┆ An         ┆ Warm       ┆ … ┆ 45.3       ┆ 2         ┆ null      ┆ ["Melt 1  │
│          ┆        ┆ excellent  ┆ Chicken A  ┆   ┆            ┆           ┆           ┆ 1/2 ozs   │
│          ┆        ┆ dish.      ┆ La King    ┆   ┆            ┆           ┆           ┆ butter,   │
│          ┆        ┆            ┆            ┆   ┆            ┆           ┆           ┆ add t…    │
└──────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [34]:
drop_cols = ["ReviewId"]
merged = merged.drop(drop_cols)

In [31]:
merged.columns

['ReviewId',
 'RecipeId',
 'Rating',
 'Review',
 'Name',
 'CookTime',
 'PrepTime',
 'TotalTime',
 'Description',
 'Images',
 'RecipeCategory',
 'Keywords',
 'RecipeIngredientParts',
 'AggregatedRating',
 'ReviewCount',
 'Calories',
 'FatContent',
 'SaturatedFatContent',
 'CholesterolContent',
 'SodiumContent',
 'CarbohydrateContent',
 'FiberContent',
 'SugarContent',
 'ProteinContent',
 'RecipeServings',
 'RecipeYield',
 'RecipeInstructions']

In [35]:
merged.write_parquet("merged.parquet")

In [38]:
merged.shape

(1401963, 26)

In [40]:
import polars as pl

df = pl.read_parquet("merged.parquet")

empty_count = df.filter(
    pl.col("Images").is_null() | (pl.col("Images").list.len() == 0)
).shape[0]

print(f"Total rows:         {len(df):,}")
print(f"Empty Images rows:  {empty_count:,}")
print(f"Filled Images rows: {len(df) - empty_count:,}")

Total rows:         1,401,963
Empty Images rows:  0
Filled Images rows: 1,401,963

In [41]:
df.head()

shape: (5, 26)
┌──────────┬────────┬────────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ RecipeId ┆ Rating ┆ Review     ┆ Name       ┆ … ┆ ProteinCon ┆ RecipeSer ┆ RecipeYie ┆ RecipeIns │
│ ---      ┆ ---    ┆ ---        ┆ ---        ┆   ┆ tent       ┆ vings     ┆ ld        ┆ tructions │
│ i32      ┆ i32    ┆ str        ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│          ┆        ┆            ┆            ┆   ┆ f64        ┆ i32       ┆ str       ┆ list[str] │
╞══════════╪════════╪════════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 992      ┆ 5      ┆ better     ┆ Jalapeno   ┆ … ┆ 4.3        ┆ 24        ┆ null      ┆ ["In a    │
│          ┆        ┆ than any   ┆ Pepper     ┆   ┆            ┆           ┆           ┆ mixing    │
│          ┆        ┆ you can    ┆ Poppers    ┆   ┆            ┆           ┆           ┆ bowl,     │
│          ┆        ┆ get at…    ┆            ┆   ┆            ┆           ┆           ┆ combine   │
│          ┆        ┆            ┆            ┆   ┆            ┆           ┆           ┆ ch…       │
│ 4384     ┆ 4      ┆ I cut back ┆ Curry Dip  ┆ … ┆ 0.2        ┆ 4         ┆ null      ┆ ["Combine │
│          ┆        ┆ on the     ┆            ┆   ┆            ┆           ┆           ┆ all in a  │
│          ┆        ┆ mayo, and  ┆            ┆   ┆            ┆           ┆           ┆ bowl and  │
│          ┆        ┆ ma…        ┆            ┆   ┆            ┆           ┆           ┆ mi…       │
│ 4523     ┆ 2      ┆ i think i  ┆ Chinese    ┆ … ┆ 43.0       ┆ 8         ┆ null      ┆ ["Combine │
│          ┆        ┆ did        ┆ Imperial   ┆   ┆            ┆           ┆           ┆ all ingre │
│          ┆        ┆ something  ┆ Palace     ┆   ┆            ┆           ┆           ┆ dients    │
│          ┆        ┆ wrong …    ┆ Genera…    ┆   ┆            ┆           ┆           ┆ for …     │
│ 7435     ┆ 5      ┆ easily the ┆ Kevin's    ┆ … ┆ 47.0       ┆ 12        ┆ null      ┆ ["Use a   │
│          ┆        ┆ best i     ┆ Best       ┆   ┆            ┆           ┆           ┆ 14 to 20  │
│          ┆        ┆ have ever  ┆ Corned     ┆   ┆            ┆           ┆           ┆ qt.       │
│          ┆        ┆ ha…        ┆ Beef       ┆   ┆            ┆           ┆           ┆ pan.",    │
│          ┆        ┆            ┆            ┆   ┆            ┆           ┆           ┆ "C…       │
│ 44       ┆ 5      ┆ An         ┆ Warm       ┆ … ┆ 45.3       ┆ 2         ┆ null      ┆ ["Melt 1  │
│          ┆        ┆ excellent  ┆ Chicken A  ┆   ┆            ┆           ┆           ┆ 1/2 ozs   │
│          ┆        ┆ dish.      ┆ La King    ┆   ┆            ┆           ┆           ┆ butter,   │
│          ┆        ┆            ┆            ┆   ┆            ┆           ┆           ┆ add t…    │
└──────────┴────────┴────────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘